channelName: "vedal987"
voices:
  - "English (America)"
  - "English (America)+Andrea"
  - "English (America)+female1"
  - "English (America)+female2"
  - "English (America)+female3"
  - "English (America)+female4"
