channelName: "vedal987"
voices:
  - "Microsoft Natasha Online (Natural) - English (Australia)"
  - "Microsoft William Online (Natural) - English (Australia)"
  - "Microsoft Clara Online (Natural) - English (Canada)"
  - "Microsoft Liam Online (Natural) - English (Canada)"
  - "Microsoft Sam Online (Natural) - English (Hongkong)"
  - "Microsoft Yan Online (Natural) - English (Hongkong)"
  - "Microsoft Neerja Online (Natural) - English (India) (Preview)"
  - "Microsoft Neerja Online (Natural) - English (India)"
  - "Microsoft Prabhat Online (Natural) - English (India)"
  - "Microsoft Connor Online (Natural) - English (Ireland)"
  - "Microsoft Emily Online (Natural) - English (Ireland)"
  - "Microsoft Asilia Online (Natural) - English (Kenya)"
  - "Microsoft Chilemba Online (Natural) - English (Kenya)"
  - "Microsoft Mitchell Online (Natural) - English (New Zealand)"
  - "Microsoft Molly Online (Natural) - English (New Zealand)"
  - "Microsoft Abeo Online (Natural) - English (Nigeria)"
  - "Microsoft Ezinne Online (Natural) - English (Nigeria)"
  - "Microsoft James Online (Natural) - English (Philippines)"
  - "Microsoft Rosa Online (Natural) - English (Philippines)"
  - "Microsoft Luna Online (Natural) - English (Singapore)"
  - "Microsoft Wayne Online (Natural) - English (Singapore)"
  - "Microsoft Leah Online (Natural) - English (South Africa)"
  - "Microsoft Luke Online (Natural) - English (South Africa)"
  - "Microsoft Elimu Online (Natural) - English (Tanzania)"
  - "Microsoft Imani Online (Natural) - English (Tanzania)"
  - "Microsoft Libby Online (Natural) - English (United Kingdom)"
  - "Microsoft Maisie Online (Natural) - English (United Kingdom)"
  - "Microsoft Ryan Online (Natural) - English (United Kingdom)"
  - "Microsoft Sonia Online (Natural) - English (United Kingdom)"
  - "Microsoft Thomas Online (Natural) - English (United Kingdom)"
  - "Microsoft AvaMultilingual Online (Natural) - English (United States)"
  - "Microsoft AndrewMultilingual Online (Natural) - English (United States)"
  - "Microsoft EmmaMultilingual Online (Natural) - English (United States)"
  - "Microsoft BrianMultilingual Online (Natural) - English (United States)"
  - "Microsoft Ava Online (Natural) - English (United States)"
  - "Microsoft Andrew Online (Natural) - English (United States)"
  - "Microsoft Emma Online (Natural) - English (United States)"
  - "Microsoft Brian Online (Natural) - English (United States)"
  - "Microsoft Ana Online (Natural) - English (United States)"
  - "Microsoft Aria Online (Natural) - English (United States)"
  - "Microsoft Christopher Online (Natural) - English (United States)"
  - "Microsoft Eric Online (Natural) - English (United States)"
  - "Microsoft Guy Online (Natural) - English (United States)"
  - "Microsoft Jenny Online (Natural) - English (United States)"
  - "Microsoft Michelle Online (Natural) - English (United States)"
  - "Microsoft Roger Online (Natural) - English (United States)"
  - "Microsoft Steffan Online (Natural) - English (United States)"
obsSettings:
  obsURL: "ws://localhost:4455"
  password: "somepassword"
  sourceName: "Chat"
filteredExps:
  - "[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_\\+.~#?&//=]*)"
