[package]
name = "kiki"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
tokio-util = { workspace = true }
shared = { path = "../shared" }
rand = "0.9.1"
env_logger = "0.11.8"
log = { workspace = true }
