channelName: "vanorsigma"
commandsDisabled: True
distractConfig:
  distractCooldown: 1800
  rotateCooldown: 300
  distractChance: 0.001
  rotateChance: 0.01
  enabled: true
remoteChatTTS: {}
standaloneSongConfig: {}

moderationConfig:
  moderatorUsers:
    - pastel8844
    - deplytha
    - asmodeus_desu
  unblockableCommands:
    - '%restart'
    - '%block'
    - '%unblock'
    - '%closemarket'
    - '%refreshVoice'
    - '%rotate'
    - '%distract'
  blockMinimumBid: 1000
  killCost: 2000
blackSilenceConfig:
  user: nikitakik228
  durationMs: 10000
  cost: 500
  karma: 50
flashbangConfig:
  cost: 500
  karma: -100
maxwellConfig:
  cost: 100
  user: 5kuli
  cooldownMs: 30000
  limit: 100
mistakeConfig:
  cost: 5000
  user: mr_auto
  karma: -1000
showImageConfig:
  cost: 10000
  user: mayoigo_qwq
  cooldownMs: 60000
  karma: -200
playAudioConfig:
  cost: 10000
  user: SpookiestSpooks
  karma: -100
selfThoughtConfig:
  cost: 5000
  karma: -200
goodNightKissConfig:
  cost: 5000
  user: pastel8844
  karma: -300
  timeoutDurationSec: 1800
setTitleConfig:
  cost: 1000
  karmaRequirement: 100
  karmaModifier: -0.3
  user: sekatsu1
karmaConfig:
  min: -5000
  max: 5000
  dingThreshold: 250
  decayRate: 0.01
  karmaMap:
    - command: '%rotate'
      karma: -100
    - command: '%distract'
      karma: -200
  togglesKarma:
    - name: Hearts
      karma: 5.0
    - name: Stars
      karma: 5.0
    - name: Undress
      karma: 50.0
modelConfig:
  initialHeartrate: 50
  blushHrThreshold: 80
  despairHrThreshold: 50
captchaConfig:
  points: 500
  karma: 100
  durationMs: 30000
checkInConfig:
  points: 999.99

soundEffects:
  - tag: "(metalpipes)"
    filePath: "https://www.myinstants.com/media/sounds/jixaw-metal-pipe-falling-sound.mp3"
  - tag: "(notification)"
    filePath: "https://www.myinstants.com/media/sounds/android-notification.mp3"
  - tag: "(wompwomp)"
    filePath: "https://www.myinstants.com/media/sounds/shylily-womp-womp_ZXYbL1F.mp3"
  - tag: "(vine)"
    filePath: "https://www.myinstants.com/media/sounds/vine-boom.mp3"
  - tag: "(ack)"
    filePath: "https://www.myinstants.com/media/sounds/ack.mp3"
  - tag: "(snore)"
    filePath: "https://www.myinstants.com/media/sounds/snore-mimimimimimi.mp3"
  - tag: "(emotionaldamage)"
    filePath: "https://www.myinstants.com/media/sounds/emotional-damage-meme.mp3"
  - tag: "(wow)"
    filePath: "https://www.myinstants.com/media/sounds/anime-wow-sound-effect.mp3"
  - tag: "(emergencymeeting)"
    filePath: "https://www.myinstants.com/media/sounds/among-us-emergency-meeting-sound-effect-hd_6pLP87j.mp3"
  - tag: "(fbiopenup)"
    filePath: "https://www.myinstants.com/media/sounds/fbi-open-up_dwLhIFf.mp3"
  - tag: "(deer)"
    filePath: "https://www.myinstants.com/media/sounds/shikanoko-nokonoko-koshitantan_93qRnvP.mp3"
  - tag: "(xp)"
    filePath: "https://www.myinstants.com/media/sounds/erro.mp3"
  - tag: "(chilling)"
    filePath: "https://www.myinstants.com/media/sounds/bing-chilling_fcdGgUc.mp3"
  - tag: "(sigma)"
    filePath: "https://www.myinstants.com/media/sounds/erm-what-the-sigma_su7GnzC.mp3"
  - tag: "(poke)"
    filePath: "https://www.myinstants.com/media/sounds/cartoon-poke.mp3"
  - tag: "(horn)"
    filePath: "https://www.myinstants.com/media/sounds/clown-horn-sound-effect_1.mp3"
  - tag: "(bruh)"
    filePath: "https://www.myinstants.com/media/sounds/movie_1.mp3"
  - tag: "(nuke)"
    filePath: "https://www.myinstants.com/media/sounds/tactical-nuke.mp3"
  - tag: "(LieMeter)"
    filePath: "https://www.myinstants.com/media/sounds/wrong-pr_krM3hvu.mp3"
  - tag: "(laugh)"
    filePath: "https://www.myinstants.com/media/sounds/laughter-short.mp3"
  - tag: "(trombone)"
    filePath: "https://www.myinstants.com/media/sounds/sadtrombone.swf.mp3"
  - tag: "(omg)"
    filePath: "https://www.myinstants.com/media/sounds/joseph-oh-my-god-green-screen.mp3"
  - tag: "(rizz)"
    filePath: "https://www.myinstants.com/media/sounds/rizz-sounds.mp3"
  - tag: "(GOODONE)"
    filePath: "https://www.myinstants.com/media/sounds/joke_drum_effect.mp3"
  - tag: "(damn)"
    filePath: "https://www.myinstants.com/media/sounds/daaamn.mp3"
  - tag: "(discord)"
    filePath: "https://www.myinstants.com/media/sounds/discord-notification.mp3"
  - tag: "(dramatic)"
    filePath: "https://www.myinstants.com/media/sounds/dramatic.swf.mp3"
  - tag: "(hallelujah)"
    filePath: "https://www.myinstants.com/media/sounds/hallelujahshort.swf.mp3"
  - tag: "(Inception)"
    filePath: "https://www.myinstants.com/media/sounds/inceptionbutton.mp3"
  - tag: "(disaster)"
    filePath: "https://www.myinstants.com/media/sounds/its-a-disaster_mixdown.mp3"
  - tag: "(trap)"
    filePath: "https://www.myinstants.com/media/sounds/adm-ackbar-its-a-trap.mp3"
  - tag: "(NOOO)"
    filePath: "https://www.myinstants.com/media/sounds/nooo.swf.mp3"
  - tag: "(NO)"
    filePath: "https://www.myinstants.com/media/sounds/engineer_no01_1.mp3"
  - tag: "(silence)"
    filePath: "https://www.myinstants.com/media/sounds/ahmed-the-dead-terrorist-silence-i-kill-you_.mp3"
  - tag: "(spaceship)"
    filePath: "https://www.myinstants.com/media/sounds/spaceship.mp3"
  - tag: "(ubi)"
    filePath: "https://www.myinstants.com/media/sounds/assassinscut4toby.mp3"
  - tag: "(whip)"
    filePath: "https://www.myinstants.com/media/sounds/crack_the_whip.mp3"
  - tag: "(why)"
    filePath: "https://www.myinstants.com/media/sounds/why.mp3"
  - tag: "(wololo)"
    filePath: "https://www.myinstants.com/media/sounds/sound-9.mp3"
  - tag: "(yeah)"
    filePath: "https://www.myinstants.com/media/sounds/sound-9______.mp3"
  - tag: "(boom)"
    filePath: "https://www.myinstants.com/media/sounds/boom-evil.mp3"
  - tag: "(groantube)"
    filePath: "https://www.myinstants.com/media/sounds/groantube-full.mp3"
  - tag: "(click)"
    filePath: "https://www.myinstants.com/media/sounds/library-of-ruina-click-sound.mp3"
  - tag: "(goodjob)"
    filePath: "https://www.myinstants.com/media/sounds/vedal-good-job.mp3"
  - tag: "(what)"
    filePath: "https://www.myinstants.com/media/sounds/vedal-what.mp3"
  - tag: "(spoiler)"
    filePath: "https://www.myinstants.com/media/sounds/neuro-spoiler.mp3"
  - tag: "(keys)"
    filePath: "https://www.myinstants.com/media/sounds/jingling-keys.mp3"
  - tag: "(sneeze)"
    filePath: "https://www.myinstants.com/media/sounds/mococo-cute-sneeze.mp3"
filteredExps:
  - "https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%.\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_\\+.~#?&//=]*)"
  - "([^(%refreshVoice)\\w\\d\\s?\\[\\]@',!-;’\\.\\?…])+"
  - "all known laws of aviation"
  - "^.{200,}$"
  - "^[!`{~].*"
  - "(?:[0-9] *){7,}"
  - "[sS]hikanoko"
